initial changes
giantswarm/cicd-tools pull request #62
Opened 2023-05-16 17:34 UTC by ericgraf

2023-05-18 07:37 UTC, AverageMarcus commented on markdown-to-slack-blocks-tool/Dockerfile
> +RUN npm ci --omit=dev
This shouldn't be needed

2023-05-18 07:37 UTC, AverageMarcus commented on markdown-to-slack-blocks-tool/Dockerfile
> +COPY . .
```suggestion
COPY server.js ./
```

2023-05-18 07:37 UTC, AverageMarcus commented on markdown-to-slack-blocks-tool/server.js
> +  console.log(blocks);
```suggestion
  console.log(blocks); 
  process.exit(0);
```

2023-05-18 07:38 UTC, AverageMarcus commented on markdown-to-slack-blocks-tool/Dockerfile
> +FROM node:lts
```suggestion
FROM node:18
```
Just in case new LTS causes break when it's switched to v20

2023-06-13 08:12 UTC, AverageMarcus requested changes

2023-06-13 08:12 UTC, AverageMarcus commented on markdown-to-slack-blocks-tool/README.md
> +IMAGE=quay.io/giantswarm/tinkerers-ci:m2b
```suggestion
IMAGE=quay.io/giantswarm/markdown-to-slack-blocks-tool:latest
```
This needs creating in Quay too.

2023-06-13 08:12 UTC, AverageMarcus commented on markdown-to-slack-blocks-tool/server.js
> +}
```suggestion
async function run() {
  let input = process.env.INPUT
      .replace("\\n", "\n")
      .replace(/<@([A-Za-z0-9]+)>/g, "&lt;@$1&gt;") // User mentions
      .replace(/<!([A-Za-z0-9\|\^]+)>/g, "&lt;!$1&gt;") // Group / Special mentions
      .replace(/<#([A-Za-z0-9]+)>/g, "&lt;#$1&gt;") // Channels
    
  let blocks = await mack.markdownToBlocks(input);
  blocks = blocks.map(b => {
    if (b.text && b.text.text) {
      b.text.text = b.text.text
          .replace(/&lt;@([A-Za-z0-9]+)&gt;/g, "<@$1>") // User mentions
          .replace(/&lt;!([A-Za-z0-9\|\^]+)&gt;/g, "<!$1>") // Group / Special mentions
          .replace(/&lt;#([A-Za-z0-9]+)&gt;/g, "<#$1>") // Channels
    }
    return b;
  })
  console.log(JSON.stringify(blocks)); 
}
```

I forget _why_ but this is the latest of the code I was using. There was some issue about links or mentions or something, right?

2023-06-13 11:48 UTC, ericgraf commented on markdown-to-slack-blocks-tool/server.js
> +}
This would have been the mentions. I ended up changing my mentions to do the input shaping but I think it's good to do it here so others don't have to do the hack.

2023-06-13 11:55 UTC, AverageMarcus approved these changes

2023-06-13 11:55 UTC, merged